from dotenv import load_dotenv
load_dotenv()
from langchain_groq import ChatGroq
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import SQLDatabaseToolkit
import os
from langchain.agents import create_agent
from langgraph.checkpoint.memory import InMemorySaver
import streamlit as st

# db=SQLDatabase.from_uri(os.getenv("DB_URI")) for postgresql
if 'db' not in st.session_state:
    st.session_state['db']=SQLDatabase.from_uri('sqlite:///Task_DB.db')
    st.session_state['db'].run("""
    create table if not exists tasks(
    id integer primary key autoincrement,
    title text not null,
    description text not null,
    status text check(status in ('pending','in progress','completed')) not null default 'pending',
    created_at timestamp default current_timestamp
    );
    """)

llm=ChatGroq(
    model="openai/gpt-oss-20b")
toolkit=SQLDatabaseToolkit(db=st.session_state['db'],llm=llm)
tools=toolkit.get_tools()
if 'memory' not in st.session_state:
    st.session_state['memory']=InMemorySaver()
sys_prompt = """
You are a task management assistant.

You can perform CRUD operations on the user's tasks using the provided database tools.

IMPORTANT:
- Use the database tools whenever the user asks about tasks.
- Do not invent task information.
- Do not expose SQL queries, database schemas, tool calls, or intermediate reasoning to the user.
- Do not show the SQL generated by the agent.
- Only provide the final result in a clean, concise format.
- For listing tasks, show only useful task information such as ID, title, description, and status.
- For create, update, or delete operations, clearly confirm whether the operation succeeded.
- If an operation fails, tell the user that it failed.
- If the user's request is ambiguous, ask for clarification.

Answer only with the information relevant to the user's request.
"""
@st.cache_resource
def get_agent():
    agent=create_agent(
        model=llm,
        tools=tools,
        checkpointer=st.session_state['memory'],
        system_prompt=sys_prompt
        )
    return agent

agent = get_agent()    

st.title("📝 Task Management AI Agent")
st.write("This AI agent can help you manage your tasks using a SQLite database. You can create, view, update, and delete tasks, as well as ask questions about your tasks.")
query=st.chat_input('Ask Anything')

if 'chat_history' not in st.session_state:
    st.session_state['chat_history']=[]

for i in st.session_state['chat_history']:
    st.chat_message(i['role']).markdown(i['content'])

if query:
    st.session_state['chat_history'].append({'role':'user','content': query})
    st.chat_message('user').markdown(query)
    with st.chat_message('ai'):
        with st.spinner('processing...'):
            res=agent.invoke(
                {'messages':[{'role':'user','content':query}]},
                {'configurable':{'thread_id':'task_agent'}},
                stream_mode='messages'
            )
            ai_container=st.chat_message('assistant')
            with ai_container:
                space= st.empty()
                message=""
                for chunk, metadata in res:
                    if metadata.get("langgraph_node") == "model":
                        if chunk.content:
                            message += chunk.content
                    space.markdown(message)
        st.session_state['chat_history'].append({'role':'assistant','content': message})
